# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: Env
  displayName: Pool Image
  type: string
  default: Lakshhna
  values:
  - Lakshhna
  - Ryan
variables:
  var1: value1
  var2: ${{ parameters.Env }}

trigger:
- main
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job:
    steps:
    - script: echo Dev! ${{ parameters.Env }} $(var1) $(var12)
      displayName: 'Run a one-line script'

- stage: QA
  displayName: QA
  jobs:
  - job:
    steps:
    - script: echo QA! ${{ parameters.Env }}
      displayName: 'Run a one-line script'