# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: Env
  displayName: Pool Image
  type: string
  default: Lakshhna
  values:
  - Lakshhna
  - Ryan

trigger:
- main
pool:
  vmImage: ubuntu-latest

stages:
- stage: Dev
  displayName: Dev
  jobs:
  - job:
    steps:
    - script: echo Dev! ${{ parameters.Env }}
      displayName: 'Run a one-line script'
